// Optional adapter integration check: set INDEXEDDB_TEST_MODULE to fake-indexeddb/auto's URL.
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
if(!process.env.INDEXEDDB_TEST_MODULE) throw new Error('Set INDEXEDDB_TEST_MODULE to an installed fake-indexeddb/auto module URL.');
await import(process.env.INDEXEDDB_TEST_MODULE);
const {IndexedDBRepository}=await import('../src/repository.js');
const load=async name=>JSON.parse(await readFile(new URL(`../data/${name}.json`,import.meta.url)));
const seed={schemaVersion:2,items:await load('inventory'),benchmarks:await load('benchmarks')};
const repo=new IndexedDBRepository('enxoval-test');
assert.deepEqual(await repo.initialize(seed),seed);
const item={...seed.items[0],id:'test-one',quantity:3};
await repo.saveItem(item);
const reopened=new IndexedDBRepository('enxoval-test');
assert.equal((await reopened.load()).items.at(-1).quantity,3);
await reopened.saveItem({...item,quantity:8});
assert.equal((await repo.load()).items.at(-1).quantity,8);
await Promise.all([repo.saveItem({...item,id:'parallel-a'}),reopened.saveItem({...item,id:'parallel-b'})]);
assert.equal((await repo.load()).items.length,194);
await repo.deleteItem(item.id);assert.equal((await repo.load()).items.length,193);
const b={...seed.benchmarks[0],id:'test-benchmark',target:12};
await repo.saveBenchmark(b);assert.equal((await repo.load()).benchmarks.at(-1).target,12);
await repo.deleteBenchmark(b.id);assert.equal((await repo.load()).benchmarks.length,46);
const before=await repo.load();
await assert.rejects(repo.saveItem({...item,quantity:-1}));
assert.deepEqual(await repo.load(),before);
await assert.rejects(repo.replaceAll({...seed,schemaVersion:2}));assert.deepEqual(await repo.load(),before);
await repo.replaceAll({schemaVersion:2,items:[],benchmarks:[]});
assert.deepEqual(await repo.initialize(seed),{schemaVersion:2,items:[],benchmarks:[]});
await repo.replaceAll(seed);assert.deepEqual(await reopened.load(),seed);
repo.db.close();reopened.db.close();
console.log('Storage contract passed: initialize, reopen, CRUD, concurrent writes, rollback, empty persistence and atomic backup restore.');
